version: 2.1
orbs:
  eb: circleci/aws-elastic-beanstalk@2.0.1
  node: circleci/node@5.1.0
workflows:
  elastic-beanstalk-workflow:
    jobs:
      - node/test:
          app-dir: ~/project/backend
      - eb/deploy:
          app-dir: ~/project/backend
          application-name: SDSU-RestRant-Deploy
          context: aws-creds
          environment-name: Sdsurestrantdeploy-env
          filters:
            branches:
              only:
                - main
          label: version-<<pipeline.number>>
          requires:
            - node/test
